name: cisco-phone-adapter-configuration-utility
fingerprint:
- path: /
  status_code: 0
  headers: {}
  keyword:
  - cisco
  - configuration utility
  favicon_hash: []
  priority: 3
- path: /
  status_code: 0
  headers: {}
  keyword:
  - login.cgi
  favicon_hash: []
  priority: 3
